name: Release

on:
  push:
    tags: [**]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download MacOS
        uses: actions/download-artifact@v1
        with:
          name: macOS-${{ github.sha }}
          path: dist

      - name: Download Linux
        uses: actions/download-artifact@v1
        with:
          name: Linux-${{ github.sha }}
          path: dist

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: Windows-${{ github.sha }}
          path: dist

      - name: Publish MacOS
        uses: actions-hub/gcloud@master
        env:
          PROJECT: loalang
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp dist/macOS-${{ github.sha }}.tar.gz gs://cdn.loalang.xyz/${{ github.ref }}-x86_64-macos.tar.gz

      - name: Publish Linux
        uses: actions-hub/gcloud@master
        env:
          PROJECT: loalang
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp dist/Linux-${{ github.sha }}.tar.gz gs://cdn.loalang.xyz/${{ github.ref }}-x86_64-linux.tar.gz

      - name: Publish Windows
        uses: actions-hub/gcloud@master
        env:
          PROJECT: loalang
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp dist/Windows-${{ github.sha }}.tar.gz gs://cdn.loalang.xyz/${{ github.ref }}-x86_64-windows.tar.gz
